#Samuel's i3status-rs config 

theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 5

# [[block]]
# block = "temperature" 
# collapsed = false
# interval = 1
# format = "{max}°"

[[block]]  # Fan speed and temperature
block = "custom"
interval = 10
command = """sensors | grep 'CPU\\|fan1' | awk '{print $2};' | tr '\n' ' ' | sed 's/.$//'"""

[[block]]
block = "load"
interval = 5
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 15
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
